#######################################
#
#     Exchequer   -   by Ratismal
#
#######################################

#Whether the plugin should send anonymous plugin statistics to mcstats.org
metrics: true